set encoding=utf8
set ruler
set ignorecase
set hlsearch
set showmatch
set noerrorbells
set novisualbell
syntax enable
colorscheme slate
set background=dark
set ffs=unix,mac,dos
set noswapfile
set nobackup
set nowritebackup
set expandtab
set smarttab
set ai
set si
set wrap
set tabstop=4
set softtabstop=4
set shiftwidth=4
set autoindent
